### PR TITLE
Royal Rumble 1.0.2

### PR DESCRIPTION
**Pull request by technodono**
- Fixed bad regions & Filters
- Updates portals
- Some text was changed
- Re spawn timer is now 5s

### CODE REVIEW

**Comment by CrazyisCreeps** [comment]
> Remeber

Also I'm pretty sure the flag carrying filter you have can be simplified. You define not carrying flag but then immediately define carrying flag but on a team. The filter will assume that players not on the team not carrying the flag will pass as false anyways, so the first not carrying flag can most likely be removed. (If that makes any sense at all, I'm not great at explaining filters)

**Comment by technodono** [comment]
Yea... I look into testing that for a later update... thanks @CrazyisCreeps

**Comment by CrazyisCreeps** [comment]
Alright got a chance to actually test to xml out, and I got a few improvements I'd like to see before merging the PR. Overall though, I'm happy with the changes you made, it's really going to improve the map.

First off, get rid of the "You may not score on yourself" regions. I believe you already filter who can use the jump pad, having a region to deny players from entering is only creating an obstruction in the playing field.

Secondly, I notice about 30% of the time I go to score, I skip right through the ring without capturing the flag. I'm not sure what exactly the issue is, but I notice it tends to happen more often when you jump into the pad rather than walking into it. Maybe extending the capture region out a block or so could fix the issue? I'd play around with it a little. For reference, this happens on the 1 point capture ring.

Lastly, fix the spelling mistake in the tip. It should be remember rather than remeber.

PS - I also notice a bunch of comments in the xml about keeping it set to night and see that you gave night vision to players. Just so you're aware, the map loads in the day rather than night.

**Comment by technodono** [comment]
@CrazyisCreeps 

- I'll remove those regions from the map

- I've had no difficulties with the rings but I'll push the regions back by 1 block towards spawn just to make it a bit longer and hopefully register quickly

- I'll fix the spelling mistake and optimise my code a bit for the filters

**Comment by technodono** [comment]
- I have night-vision effects because the house and spawn areas of the map look too dark without it and I couldn't find great places to put light sources in there that look nice

that's it

**Comment by technodono** [comment]
Fixed stuff mentioned 👍

**Comment by CrazyisCreeps** [comment]
Awesome, thanks for doing those edits for me! Can't wait to test out these new changes 😄

**Pull request merged**
