### PR TITLE
Factorio Gridbase 1.3.0 

### PR DESCRIPTION
**Pull request by Omote23**
Major XML changes
Spawn location is changed a bit
Potion on the spawn Kit is amended. 
New gimmick : add time-passed gear upgrade. each 20 minutes passed, you will receive an upgraded potion until 1 hour. 
These potions on the spawn kits have lots of merits and demerits. so use it correctly. 

List of potions on spawn kit
~20min : Seal (Slowness 15s instant damage 1)
20min~40min : Drive (Speed 1 60s, weakness 1 60s), Seal
40min~60min : Accelerate (Speed 1 60s), Plague (90s hunger 90s slow digging)
60min~ : Accelerated Depreciation (speed 2 60s -6 hearts), Liquidate (60s hunger 2 60s slow digging)

The intention of these potions is to reduce the stalemate situation and induce an ideal match duration (10~30min) the more time passes attackers will be far easier to attack.

In addition, I'm making a completely different factorio based map called "factorio mainbus" coworking with technodono. 
Similar layout, but completely different.

### CODE REVIEW

**Comment by CoWinkKeyDinkInc** [comment]
I've fixed your merge conflict, is the XML you posted still the correct one?

**Comment by Omote23** [comment]
> I've fixed your merge conflict, is the XML you posted still the correct one?

It seems that most of the new XML is deleted.

**Comment by CoWinkKeyDinkInc** [comment]
Try committing it again

**Comment by Omote23** [comment]
> Try committing it again

ok Wait a minute

**Pull request closed without merging**
